-- keremozer.com
create database IlilceDB;
Go
USE IlilceDB

create table Iller(
IlID int not null primary key identity(1,1),
Il nvarchar(100)
)
create table Ilceler(
IlceID int not null primary key identity(1,1),
IlID int foreign key references Iller(IlID),
Ilce nvarchar(100)
)
-- 1 -10
insert into Iller (Il) values ('Adana')
insert into Iller (Il) values ('Adýyaman')
insert into Iller (Il) values ('Afyonkarahisar')
insert into Iller (Il) values ('Aðrý')
insert into Iller (Il) values ('Amasya')
insert into Iller (Il) values ('Ankara')
insert into Iller (Il) values ('Antalya')
insert into Iller (Il) values ('Artvin')
insert into Iller (Il) values ('Aydýn')
insert into Iller (Il) values ('Balýkesir')
-- 10 - 20
insert into Iller (Il) values ('Bilecik')
insert into Iller (Il) values ('Bingöl')
insert into Iller (Il) values ('Bitlis')
insert into Iller (Il) values ('Bolu')
insert into Iller (Il) values ('Burdur')
insert into Iller (Il) values ('Bursa')
insert into Iller (Il) values ('Çanakkale')
insert into Iller (Il) values ('Çankýrý')
insert into Iller (Il) values ('Çorum')
insert into Iller (Il) values ('Denizli')
-- 20 - 30
insert into Iller (Il) values ('Diyarbakýr')
insert into Iller (Il) values ('Edirne')
insert into Iller (Il) values ('Elazýð')
insert into Iller (Il) values ('Erzincan')
insert into Iller (Il) values ('Erzurum')
insert into Iller (Il) values ('Eskiþehir')
insert into Iller (Il) values ('Gaziantep')
insert into Iller (Il) values ('Giresun')
insert into Iller (Il) values ('Gümüþhane')
insert into Iller (Il) values ('Hakkari')
-- 30 - 40
insert into Iller (Il) values ('Hatay')
insert into Iller (Il) values ('Isparta')
insert into Iller (Il) values ('Mersin')
insert into Iller (Il) values ('Ýstanbul')
insert into Iller (Il) values ('Ýzmir')
insert into Iller (Il) values ('Kars')
insert into Iller (Il) values ('Kastamonu')
insert into Iller (Il) values ('Kayseri')
insert into Iller (Il) values ('Kýrklareli')
insert into Iller (Il) values ('Kýrþehir')
-- 40 - 50
insert into Iller (Il) values ('Kocaeli')
insert into Iller (Il) values ('Konya')
insert into Iller (Il) values ('Kütahya')
insert into Iller (Il) values ('Malatya')
insert into Iller (Il) values ('Manisa')
insert into Iller (Il) values ('Kahramanmaraþ')
insert into Iller (Il) values ('Mardin')
insert into Iller (Il) values ('Muðla')
insert into Iller (Il) values ('Muþ')
insert into Iller (Il) values ('Nevþehir')
-- 50 - 60
insert into Iller (Il) values ('Niðde')
insert into Iller (Il) values ('Ordu')
insert into Iller (Il) values ('Rize')
insert into Iller (Il) values ('Sakarya')
insert into Iller (Il) values ('Samsun')
insert into Iller (Il) values ('Siirt')
insert into Iller (Il) values ('Sinop')
insert into Iller (Il) values ('Sivas')
insert into Iller (Il) values ('Tekirdað')
insert into Iller (Il) values ('Tokat')
-- 60 - 70
insert into Iller (Il) values ('Trabzon')
insert into Iller (Il) values ('Tunceli')
insert into Iller (Il) values ('Þanlýurfa')
insert into Iller (Il) values ('Uþak')
insert into Iller (Il) values ('Van')
insert into Iller (Il) values ('Yozgat')
insert into Iller (Il) values ('Zonguldak')
insert into Iller (Il) values ('Aksaray')
insert into Iller (Il) values ('Bayburt')
insert into Iller (Il) values ('Karaman')
-- 70 - 81
insert into Iller (Il) values ('Kýrýkkale')
insert into Iller (Il) values ('Batman')
insert into Iller (Il) values ('Þýrnak')
insert into Iller (Il) values ('Bartýn')
insert into Iller (Il) values ('Ardahan')
insert into Iller (Il) values ('Iðdýr')
insert into Iller (Il) values ('Yalova')
insert into Iller (Il) values ('Karabük')
insert into Iller (Il) values ('Kilis')
insert into Iller (Il) values ('Osmaniye')
insert into Iller (Il) values ('Düzce')

-- 01 Ýlcesi 
insert into Ilceler (IlID,Ilce) values (1,'Aladað')
insert into Ilceler (IlID,Ilce) values (1,'Ceyhan')
insert into Ilceler (IlID,Ilce) values (1,'Çukurova')
insert into Ilceler (IlID,Ilce) values (1,'Feke')
insert into Ilceler (IlID,Ilce) values (1,'Ýmamoðlu')
insert into Ilceler (IlID,Ilce) values (1,'Karaisalý')
insert into Ilceler (IlID,Ilce) values (1,'Karataþ')
insert into Ilceler (IlID,Ilce) values (1,'Kozan')
insert into Ilceler (IlID,Ilce) values (1,'Pozantý')
insert into Ilceler (IlID,Ilce) values (1,'Saimbeyli')
insert into Ilceler (IlID,Ilce) values (1,'Sarýçam')
insert into Ilceler (IlID,Ilce) values (1,'Tufanbeyli')
insert into Ilceler (IlID,Ilce) values (1,'Yumurtalýk')
insert into Ilceler (IlID,Ilce) values (1,'Yüreðir')

-- 02 Ýlcesi
insert into Ilceler (IlID,Ilce) values (2,'Besni')
insert into Ilceler (IlID,Ilce) values (2,'Çelikhan')
insert into Ilceler (IlID,Ilce) values (2,'Gerger')
insert into Ilceler (IlID,Ilce) values (2,'Gölbaþý')
insert into Ilceler (IlID,Ilce) values (2,'Kahta')
insert into Ilceler (IlID,Ilce) values (2,'Merkez')
insert into Ilceler (IlID,Ilce) values (2,'Samsat')
insert into Ilceler (IlID,Ilce) values (2,'Sincik')
insert into Ilceler (IlID,Ilce) values (2,'Tut')

-- 03 Ýlcesi
insert into Ilceler (IlID,Ilce) values (3,'Baþmakçý')
insert into Ilceler (IlID,Ilce) values (3,'Bayat')
insert into Ilceler (IlID,Ilce) values (3,'Bolvadin')
insert into Ilceler (IlID,Ilce) values (3,'Çay')
insert into Ilceler (IlID,Ilce) values (3,'Çobanlar')
insert into Ilceler (IlID,Ilce) values (3,'Dazkýrý')
insert into Ilceler (IlID,Ilce) values (3,'Dinar')
insert into Ilceler (IlID,Ilce) values (3,'Emirdað')
insert into Ilceler (IlID,Ilce) values (3,'Evciler')
insert into Ilceler (IlID,Ilce) values (3,'Hocalar')
insert into Ilceler (IlID,Ilce) values (3,'Ýhsaniye')
insert into Ilceler (IlID,Ilce) values (3,'Ýscehisar')
insert into Ilceler (IlID,Ilce) values (3,'Kýzýlören')
insert into Ilceler (IlID,Ilce) values (3,'Merkez')
insert into Ilceler (IlID,Ilce) values (3,'Sandýklý')
insert into Ilceler (IlID,Ilce) values (3,'Sultandaðý')
insert into Ilceler (IlID,Ilce) values (3,'Þuhut')

-- 04 Ýlcesi
insert into Ilceler (IlID,Ilce) values (4,'Diyadin')
insert into Ilceler (IlID,Ilce) values (4,'Doðubayazýt')
insert into Ilceler (IlID,Ilce) values (4,'Eleþkirt')
insert into Ilceler (IlID,Ilce) values (4,'Hamur')
insert into Ilceler (IlID,Ilce) values (4,'Merkez')
insert into Ilceler (IlID,Ilce) values (4,'Patnos')
insert into Ilceler (IlID,Ilce) values (4,'Taþlýçay')
insert into Ilceler (IlID,Ilce) values (4,'Tutak')

-- 05 Ýlcesi
insert into Ilceler (IlID,Ilce) values (5,'Göynücek')
insert into Ilceler (IlID,Ilce) values (5,'Gümüþhacýköy')
insert into Ilceler (IlID,Ilce) values (5,'Hamamözü')
insert into Ilceler (IlID,Ilce) values (5,'Merkez')
insert into Ilceler (IlID,Ilce) values (5,'Merzifon')
insert into Ilceler (IlID,Ilce) values (5,'Suluova')
insert into Ilceler (IlID,Ilce) values (5,'Taþova')

-- 06 Ýlcesi
insert into Ilceler (IlID,Ilce) values (6,'Akyurt')
insert into Ilceler (IlID,Ilce) values (6,'Altýndað')
insert into Ilceler (IlID,Ilce) values (6,'Ayaþ')
insert into Ilceler (IlID,Ilce) values (6,'Bala')
insert into Ilceler (IlID,Ilce) values (6,'Beypazarý')
insert into Ilceler (IlID,Ilce) values (6,'Çamlýdere')
insert into Ilceler (IlID,Ilce) values (6,'Çankaya')
insert into Ilceler (IlID,Ilce) values (6,'Çubuk')
insert into Ilceler (IlID,Ilce) values (6,'Elmadað')
insert into Ilceler (IlID,Ilce) values (6,'Etimesgut')
insert into Ilceler (IlID,Ilce) values (6,'Evren')
insert into Ilceler (IlID,Ilce) values (6,'Gölbaþý')
insert into Ilceler (IlID,Ilce) values (6,'Güdül')
insert into Ilceler (IlID,Ilce) values (6,'Haymana')
insert into Ilceler (IlID,Ilce) values (6,'Kalecik')
insert into Ilceler (IlID,Ilce) values (6,'Kazan')
insert into Ilceler (IlID,Ilce) values (6,'Keçiören')
insert into Ilceler (IlID,Ilce) values (6,'Kýzýlcahamam')
insert into Ilceler (IlID,Ilce) values (6,'Mamak')
insert into Ilceler (IlID,Ilce) values (6,'Nallýhan')
insert into Ilceler (IlID,Ilce) values (6,'Polatlý')
insert into Ilceler (IlID,Ilce) values (6,'Pursaklar')
insert into Ilceler (IlID,Ilce) values (6,'Sincan')
insert into Ilceler (IlID,Ilce) values (6,'Þereflikoçhisar')
insert into Ilceler (IlID,Ilce) values (6,'Yenimahalle')

-- 07 Ýlcesi
insert into Ilceler (IlID,Ilce) values (7,'Akseki')
insert into Ilceler (IlID,Ilce) values (7,'Aksu')
insert into Ilceler (IlID,Ilce) values (7,'Alanya')
insert into Ilceler (IlID,Ilce) values (7,'Demre')
insert into Ilceler (IlID,Ilce) values (7,'Döþemealtý')
insert into Ilceler (IlID,Ilce) values (7,'Elmalý')
insert into Ilceler (IlID,Ilce) values (7,'Finike')
insert into Ilceler (IlID,Ilce) values (7,'Gazipaþa')
insert into Ilceler (IlID,Ilce) values (7,'Gündoðmuþ')
insert into Ilceler (IlID,Ilce) values (7,'Ýbradý')
insert into Ilceler (IlID,Ilce) values (7,'Kaþ')
insert into Ilceler (IlID,Ilce) values (7,'Kemer')
insert into Ilceler (IlID,Ilce) values (7,'Kepez')
insert into Ilceler (IlID,Ilce) values (7,'Konyaaltý')
insert into Ilceler (IlID,Ilce) values (7,'Korkuteli')
insert into Ilceler (IlID,Ilce) values (7,'Kumluca')
insert into Ilceler (IlID,Ilce) values (7,'Manavgat')
insert into Ilceler (IlID,Ilce) values (7,'Muratpaþa')
insert into Ilceler (IlID,Ilce) values (7,'Serik')
--- keremozer.com
-- 08 Ýlçesi 
insert into Ilceler (IlID,Ilce) values (8,'Ardanuç')
insert into Ilceler (IlID,Ilce) values (8,'Arhavi')
insert into Ilceler (IlID,Ilce) values (8,'Borçka')
insert into Ilceler (IlID,Ilce) values (8,'Hopa')
insert into Ilceler (IlID,Ilce) values (8,'Merkez')
insert into Ilceler (IlID,Ilce) values (8,'Murgul')
insert into Ilceler (IlID,Ilce) values (8,'Þavþat')
insert into Ilceler (IlID,Ilce) values (8,'Yusufeli')

-- 09 Ýlçesi 
insert into Ilceler (IlID,Ilce) values (9,'Bozdoðan')
insert into Ilceler (IlID,Ilce) values (9,'Buharkent')
insert into Ilceler (IlID,Ilce) values (9,'Çine')
insert into Ilceler (IlID,Ilce) values (9,'Didim')
insert into Ilceler (IlID,Ilce) values (9,'Efeler')
insert into Ilceler (IlID,Ilce) values (9,'Germencik')
insert into Ilceler (IlID,Ilce) values (9,'Ýncirliova')
insert into Ilceler (IlID,Ilce) values (9,'Karacasu')
insert into Ilceler (IlID,Ilce) values (9,'Karpuzlu')
insert into Ilceler (IlID,Ilce) values (9,'Koçarlý')
insert into Ilceler (IlID,Ilce) values (9,'Köþk')
insert into Ilceler (IlID,Ilce) values (9,'Kuþadasý')
insert into Ilceler (IlID,Ilce) values (9,'Kuyucak')
insert into Ilceler (IlID,Ilce) values (9,'Nazilli')
insert into Ilceler (IlID,Ilce) values (9,'Söke')
insert into Ilceler (IlID,Ilce) values (9,'Sultanhisar')
insert into Ilceler (IlID,Ilce) values (9,'Yenipazar')

-- 10 Ýlçesi 
insert into Ilceler (IlID,Ilce) values (10,'Altýeylül')
insert into Ilceler (IlID,Ilce) values (10,'Ayvalýk')
insert into Ilceler (IlID,Ilce) values (10,'Balya')
insert into Ilceler (IlID,Ilce) values (10,'Bandýrma')
insert into Ilceler (IlID,Ilce) values (10,'Bigadiç')
insert into Ilceler (IlID,Ilce) values (10,'Burhaniye')
insert into Ilceler (IlID,Ilce) values (10,'Dursunbey')
insert into Ilceler (IlID,Ilce) values (10,'Edremit')
insert into Ilceler (IlID,Ilce) values (10,'Erdek')
insert into Ilceler (IlID,Ilce) values (10,'Gömeç')
insert into Ilceler (IlID,Ilce) values (10,'Gönen')
insert into Ilceler (IlID,Ilce) values (10,'Havran')
insert into Ilceler (IlID,Ilce) values (10,'Ývrindi')
insert into Ilceler (IlID,Ilce) values (10,'Karesi')
insert into Ilceler (IlID,Ilce) values (10,'Kepsut')
insert into Ilceler (IlID,Ilce) values (10,'Manyas')
insert into Ilceler (IlID,Ilce) values (10,'Marmara')
insert into Ilceler (IlID,Ilce) values (10,'Savaþtepe')
insert into Ilceler (IlID,Ilce) values (10,'Sýndýrgý')
insert into Ilceler (IlID,Ilce) values (10,'Susurluk')

-- 11 Ýlçesi
insert into Ilceler (IlID,Ilce) values (11,'Bozüyük')
insert into Ilceler (IlID,Ilce) values (11,'Gölpazarý')
insert into Ilceler (IlID,Ilce) values (11,'Ýnhisar')
insert into Ilceler (IlID,Ilce) values (11,'Merkez')
insert into Ilceler (IlID,Ilce) values (11,'Osmaneli')
insert into Ilceler (IlID,Ilce) values (11,'Pazaryeri')
insert into Ilceler (IlID,Ilce) values (11,'Söðüt')
insert into Ilceler (IlID,Ilce) values (11,'Yenipazar')

-- 12 Ýlçesi
insert into Ilceler (IlID,Ilce) values (12,'Adaklý')
insert into Ilceler (IlID,Ilce) values (12,'Genç')
insert into Ilceler (IlID,Ilce) values (12,'Karlýova')
insert into Ilceler (IlID,Ilce) values (12,'Kiðý')
insert into Ilceler (IlID,Ilce) values (12,'Merkez')
insert into Ilceler (IlID,Ilce) values (12,'Solhan')
insert into Ilceler (IlID,Ilce) values (12,'Yayladere')
insert into Ilceler (IlID,Ilce) values (12,'Yedisu')

-- 13 Ýlçesi
insert into Ilceler (IlID,Ilce) values (13,'Adilcevaz')
insert into Ilceler (IlID,Ilce) values (13,'Ahlat')
insert into Ilceler (IlID,Ilce) values (13,'Güroymak')
insert into Ilceler (IlID,Ilce) values (13,'Hizan')
insert into Ilceler (IlID,Ilce) values (13,'Merkez')
insert into Ilceler (IlID,Ilce) values (13,'Mutki')
insert into Ilceler (IlID,Ilce) values (13,'Tatvan')

-- 14 Ýlçesi
insert into Ilceler (IlID,Ilce) values (14,'Dörtdivan')
insert into Ilceler (IlID,Ilce) values (14,'Gerede')
insert into Ilceler (IlID,Ilce) values (14,'Göynük')
insert into Ilceler (IlID,Ilce) values (14,'Kýbrýscýk')
insert into Ilceler (IlID,Ilce) values (14,'Mengen')
insert into Ilceler (IlID,Ilce) values (14,'Merkez')
insert into Ilceler (IlID,Ilce) values (14,'Mudurnu')
insert into Ilceler (IlID,Ilce) values (14,'Seben')
insert into Ilceler (IlID,Ilce) values (14,'Yeniçaða')

-- 15 Ýlçesi
insert into Ilceler (IlID,Ilce) values (15,'Aðlasun')
insert into Ilceler (IlID,Ilce) values (15,'Altýnyayla')
insert into Ilceler (IlID,Ilce) values (15,'Bucak')
insert into Ilceler (IlID,Ilce) values (15,'Çavdýr')
insert into Ilceler (IlID,Ilce) values (15,'Çeltikçi')
insert into Ilceler (IlID,Ilce) values (15,'Gölhisar')
insert into Ilceler (IlID,Ilce) values (15,'Karamanlý')
insert into Ilceler (IlID,Ilce) values (15,'Kemer')
insert into Ilceler (IlID,Ilce) values (15,'Merkez')
insert into Ilceler (IlID,Ilce) values (15,'Tefenni')
insert into Ilceler (IlID,Ilce) values (15,'Yeþilova')

-- 16 Ýlçesi
insert into Ilceler (IlID,Ilce) values (16,'Büyükorhan')
insert into Ilceler (IlID,Ilce) values (16,'Gemlik')
insert into Ilceler (IlID,Ilce) values (16,'Gürsu')
insert into Ilceler (IlID,Ilce) values (16,'Harmancýk')
insert into Ilceler (IlID,Ilce) values (16,'Ýnegöl')
insert into Ilceler (IlID,Ilce) values (16,'Ýznik')
insert into Ilceler (IlID,Ilce) values (16,'Karacabey')
insert into Ilceler (IlID,Ilce) values (16,'Keles')
insert into Ilceler (IlID,Ilce) values (16,'Kestel')
insert into Ilceler (IlID,Ilce) values (16,'Mudanya')
insert into Ilceler (IlID,Ilce) values (16,'Mustafa Kemal Paþa')
insert into Ilceler (IlID,Ilce) values (16,'Nilüfer')
insert into Ilceler (IlID,Ilce) values (16,'Orhaneli')
insert into Ilceler (IlID,Ilce) values (16,'Orhangazi')
insert into Ilceler (IlID,Ilce) values (16,'Osmangazi')
insert into Ilceler (IlID,Ilce) values (16,'Yeniþehir')
insert into Ilceler (IlID,Ilce) values (16,'Yýldýrým')

-- 17 Ýlçesi
insert into Ilceler (IlID,Ilce) values (17,'Ayvacýk')
insert into Ilceler (IlID,Ilce) values (17,'Bayramiç')
insert into Ilceler (IlID,Ilce) values (17,'Biga')
insert into Ilceler (IlID,Ilce) values (17,'Çan')
insert into Ilceler (IlID,Ilce) values (17,'Eceabat')
insert into Ilceler (IlID,Ilce) values (17,'Ezine')
insert into Ilceler (IlID,Ilce) values (17,'Gelibolu')
insert into Ilceler (IlID,Ilce) values (17,'Gökçeada')
insert into Ilceler (IlID,Ilce) values (17,'Lapseki')
insert into Ilceler (IlID,Ilce) values (17,'Merkez')
insert into Ilceler (IlID,Ilce) values (17,'Yenice')

-- 18 Ýlçesi
insert into Ilceler (IlID,Ilce) values (18,'Atkaracalar')
insert into Ilceler (IlID,Ilce) values (18,'Bayramören')
insert into Ilceler (IlID,Ilce) values (18,'Çerkeþ')
insert into Ilceler (IlID,Ilce) values (18,'Eldivan')
insert into Ilceler (IlID,Ilce) values (18,'Ilgaz')
insert into Ilceler (IlID,Ilce) values (18,'Kýzýlýrmak')
insert into Ilceler (IlID,Ilce) values (18,'Korgun')
insert into Ilceler (IlID,Ilce) values (18,'Kurþunlu')
insert into Ilceler (IlID,Ilce) values (18,'Merkez')
insert into Ilceler (IlID,Ilce) values (18,'Orta')
insert into Ilceler (IlID,Ilce) values (18,'Þabanözü')
insert into Ilceler (IlID,Ilce) values (18,'Yapraklý')
--- keremozer.com
-- 19 Ýlçesi
insert into Ilceler (IlID,Ilce) values (19,'Alaca')
insert into Ilceler (IlID,Ilce) values (19,'Bayat')
insert into Ilceler (IlID,Ilce) values (19,'Boðazkale')
insert into Ilceler (IlID,Ilce) values (19,'Dodurga')
insert into Ilceler (IlID,Ilce) values (19,'Ýskilip')
insert into Ilceler (IlID,Ilce) values (19,'Kargý')
insert into Ilceler (IlID,Ilce) values (19,'Laçin')
insert into Ilceler (IlID,Ilce) values (19,'Mecitözü')
insert into Ilceler (IlID,Ilce) values (19,'Merkez')
insert into Ilceler (IlID,Ilce) values (19,'Oðuzlar')
insert into Ilceler (IlID,Ilce) values (19,'Ortaköy')
insert into Ilceler (IlID,Ilce) values (19,'Osmancýk')
insert into Ilceler (IlID,Ilce) values (19,'Sungurlu')
insert into Ilceler (IlID,Ilce) values (19,'Uðurludað')

-- 20 Ýlçesi
insert into Ilceler (IlID,Ilce) values (20,'Acýpayam')
insert into Ilceler (IlID,Ilce) values (20,'Babadað')
insert into Ilceler (IlID,Ilce) values (20,'Baklan')
insert into Ilceler (IlID,Ilce) values (20,'Bekilli')
insert into Ilceler (IlID,Ilce) values (20,'Beyaðaç')
insert into Ilceler (IlID,Ilce) values (20,'Bozkurt')
insert into Ilceler (IlID,Ilce) values (20,'Buldan')
insert into Ilceler (IlID,Ilce) values (20,'Çal')
insert into Ilceler (IlID,Ilce) values (20,'Çameli')
insert into Ilceler (IlID,Ilce) values (20,'Çardak')
insert into Ilceler (IlID,Ilce) values (20,'Çivril')
insert into Ilceler (IlID,Ilce) values (20,'Güney')
insert into Ilceler (IlID,Ilce) values (20,'Honaz')
insert into Ilceler (IlID,Ilce) values (20,'Kale')
insert into Ilceler (IlID,Ilce) values (20,'Merkezefendi')
insert into Ilceler (IlID,Ilce) values (20,'Pamukkale')
insert into Ilceler (IlID,Ilce) values (20,'Sarayköy')
insert into Ilceler (IlID,Ilce) values (20,'Serinhisar')
insert into Ilceler (IlID,Ilce) values (20,'Tavas')

-- 21 Ýlçesi
insert into Ilceler (IlID,Ilce) values (21,'Baðlar')
insert into Ilceler (IlID,Ilce) values (21,'Bismil')
insert into Ilceler (IlID,Ilce) values (21,'Çermik')
insert into Ilceler (IlID,Ilce) values (21,'Çýnar')
insert into Ilceler (IlID,Ilce) values (21,'Çüngüþ')
insert into Ilceler (IlID,Ilce) values (21,'Dicle')
insert into Ilceler (IlID,Ilce) values (21,'Eðil')
insert into Ilceler (IlID,Ilce) values (21,'Ergani')
insert into Ilceler (IlID,Ilce) values (21,'Hani')
insert into Ilceler (IlID,Ilce) values (21,'Hazro')
insert into Ilceler (IlID,Ilce) values (21,'Kayapýnar')
insert into Ilceler (IlID,Ilce) values (21,'Kocaköy')
insert into Ilceler (IlID,Ilce) values (21,'Kulp')
insert into Ilceler (IlID,Ilce) values (21,'Lice')
insert into Ilceler (IlID,Ilce) values (21,'Silvan')
insert into Ilceler (IlID,Ilce) values (21,'Sur')
insert into Ilceler (IlID,Ilce) values (21,'Yeniþehir')

-- 22 Ýlçesi
insert into Ilceler (IlID,Ilce) values (22,'Enez')
insert into Ilceler (IlID,Ilce) values (22,'Havsa')
insert into Ilceler (IlID,Ilce) values (22,'Ýpsala')
insert into Ilceler (IlID,Ilce) values (22,'Keþan')
insert into Ilceler (IlID,Ilce) values (22,'Lalapaþa')
insert into Ilceler (IlID,Ilce) values (22,'Meriç')
insert into Ilceler (IlID,Ilce) values (22,'Merkez')
insert into Ilceler (IlID,Ilce) values (22,'Süloðlu')
insert into Ilceler (IlID,Ilce) values (22,'Uzunköprü')

-- 23 Ýlçesi
insert into Ilceler (IlID,Ilce) values (23,'Aðýn')
insert into Ilceler (IlID,Ilce) values (23,'Alacakaya')
insert into Ilceler (IlID,Ilce) values (23,'Arýcak')
insert into Ilceler (IlID,Ilce) values (23,'Baskil')
insert into Ilceler (IlID,Ilce) values (23,'Karakoçan')
insert into Ilceler (IlID,Ilce) values (23,'Keban')
insert into Ilceler (IlID,Ilce) values (23,'Kovancýlar')
insert into Ilceler (IlID,Ilce) values (23,'Maden')
insert into Ilceler (IlID,Ilce) values (23,'Merkez')
insert into Ilceler (IlID,Ilce) values (23,'Palu')
insert into Ilceler (IlID,Ilce) values (23,'Sivrice')


-- 24 Ýlçesi
insert into Ilceler (IlID,Ilce) values (24,'Çayýrlý')
insert into Ilceler (IlID,Ilce) values (24,'Ýliç')
insert into Ilceler (IlID,Ilce) values (24,'Kemah')
insert into Ilceler (IlID,Ilce) values (24,'Kemaliye')
insert into Ilceler (IlID,Ilce) values (24,'Merkez')
insert into Ilceler (IlID,Ilce) values (24,'Otlukbeli')
insert into Ilceler (IlID,Ilce) values (24,'Refahiye')
insert into Ilceler (IlID,Ilce) values (24,'Tercan')
insert into Ilceler (IlID,Ilce) values (24,'Üzümlü')

-- 25 Ýlçesi
insert into Ilceler (IlID,Ilce) values (25,'Aþkale')
insert into Ilceler (IlID,Ilce) values (25,'Aziziye')
insert into Ilceler (IlID,Ilce) values (25,'Çat')
insert into Ilceler (IlID,Ilce) values (25,'Hýnýs')
insert into Ilceler (IlID,Ilce) values (25,'Horasan')
insert into Ilceler (IlID,Ilce) values (25,'Ýspir')
insert into Ilceler (IlID,Ilce) values (25,'Karaçoban')
insert into Ilceler (IlID,Ilce) values (25,'Karayazý')
insert into Ilceler (IlID,Ilce) values (25,'Köprüköy')
insert into Ilceler (IlID,Ilce) values (25,'Narman')
insert into Ilceler (IlID,Ilce) values (25,'Oltu')
insert into Ilceler (IlID,Ilce) values (25,'Olur')
insert into Ilceler (IlID,Ilce) values (25,'Palandöken')
insert into Ilceler (IlID,Ilce) values (25,'Pasinler')
insert into Ilceler (IlID,Ilce) values (25,'Pazaryolu')
insert into Ilceler (IlID,Ilce) values (25,'Þenkaya')
insert into Ilceler (IlID,Ilce) values (25,'Tekman')
insert into Ilceler (IlID,Ilce) values (25,'Tortum')
insert into Ilceler (IlID,Ilce) values (25,'Uzundere')
insert into Ilceler (IlID,Ilce) values (25,'Yakutiye')

-- 26 Ýlçesi
insert into Ilceler (IlID,Ilce) values (26,'Alpu')
insert into Ilceler (IlID,Ilce) values (26,'Beylikova')
insert into Ilceler (IlID,Ilce) values (26,'Çifteler')
insert into Ilceler (IlID,Ilce) values (26,'Günyüzü')
insert into Ilceler (IlID,Ilce) values (26,'Han')
insert into Ilceler (IlID,Ilce) values (26,'Ýnönü')
insert into Ilceler (IlID,Ilce) values (26,'Mahmudiye')
insert into Ilceler (IlID,Ilce) values (26,'Mihalgazi')
insert into Ilceler (IlID,Ilce) values (26,'Mihalýççýk')
insert into Ilceler (IlID,Ilce) values (26,'Odunpazarý')
insert into Ilceler (IlID,Ilce) values (26,'Sarýcakaya')
insert into Ilceler (IlID,Ilce) values (26,'Seyitgazi')
insert into Ilceler (IlID,Ilce) values (26,'Sivrihisar')
insert into Ilceler (IlID,Ilce) values (26,'Tepebaþý')
--- keremozer.com
-- 27 Ýlçesi
insert into Ilceler (IlID,Ilce) values (27,'Araban')
insert into Ilceler (IlID,Ilce) values (27,'Ýslahiye')
insert into Ilceler (IlID,Ilce) values (27,'Karkamýþ')
insert into Ilceler (IlID,Ilce) values (27,'Nizip')
insert into Ilceler (IlID,Ilce) values (27,'Nurdaðý')
insert into Ilceler (IlID,Ilce) values (27,'Oðuzeli')
insert into Ilceler (IlID,Ilce) values (27,'Þahinbey')
insert into Ilceler (IlID,Ilce) values (27,'Þahinbey')
insert into Ilceler (IlID,Ilce) values (27,'Þehitkamil')
insert into Ilceler (IlID,Ilce) values (27,'Yavuzeli')

-- 28 Ýlçesi
insert into Ilceler (IlID,Ilce) values (28,'Alucra')
insert into Ilceler (IlID,Ilce) values (28,'Bulancak')
insert into Ilceler (IlID,Ilce) values (28,'Çamoluk')
insert into Ilceler (IlID,Ilce) values (28,'Çanakçý')
insert into Ilceler (IlID,Ilce) values (28,'Dereli')
insert into Ilceler (IlID,Ilce) values (28,'Doðankent')
insert into Ilceler (IlID,Ilce) values (28,'Espiye')
insert into Ilceler (IlID,Ilce) values (28,'Eynesil')
insert into Ilceler (IlID,Ilce) values (28,'Görele')
insert into Ilceler (IlID,Ilce) values (28,'Güce')
insert into Ilceler (IlID,Ilce) values (28,'Keþap')
insert into Ilceler (IlID,Ilce) values (28,'Merkez')
insert into Ilceler (IlID,Ilce) values (28,'Piraziz')
insert into Ilceler (IlID,Ilce) values (28,'Þebinkarahisar')
insert into Ilceler (IlID,Ilce) values (28,'Tirebolu')
insert into Ilceler (IlID,Ilce) values (28,'Yaðlýdere')

-- 29 Ýlçesi
insert into Ilceler (IlID,Ilce) values (29,'Kelkit')
insert into Ilceler (IlID,Ilce) values (29,'Köse')
insert into Ilceler (IlID,Ilce) values (29,'Kürtün')
insert into Ilceler (IlID,Ilce) values (29,'Merkez')
insert into Ilceler (IlID,Ilce) values (29,'Þiran')
insert into Ilceler (IlID,Ilce) values (29,'Torul')

-- 30 Ýlçesi
insert into Ilceler (IlID,Ilce) values (30,'Çukurca')
insert into Ilceler (IlID,Ilce) values (30,'Merkez')
insert into Ilceler (IlID,Ilce) values (30,'Þemdinli')
insert into Ilceler (IlID,Ilce) values (30,'Yüksekova')

-- 31 Ýlçesi
insert into Ilceler (IlID,Ilce) values (31,'Altýnözü')
insert into Ilceler (IlID,Ilce) values (31,'Antakya')
insert into Ilceler (IlID,Ilce) values (31,'Arsuz')
insert into Ilceler (IlID,Ilce) values (31,'Belen')
insert into Ilceler (IlID,Ilce) values (31,'Defne')
insert into Ilceler (IlID,Ilce) values (31,'Dörtyol')
insert into Ilceler (IlID,Ilce) values (31,'Erzin')
insert into Ilceler (IlID,Ilce) values (31,'Hassa')
insert into Ilceler (IlID,Ilce) values (31,'Ýskenderun')
insert into Ilceler (IlID,Ilce) values (31,'Kýrýkhan')
insert into Ilceler (IlID,Ilce) values (31,'Kumlu')
insert into Ilceler (IlID,Ilce) values (31,'Payas')
insert into Ilceler (IlID,Ilce) values (31,'Reyhanlý')
insert into Ilceler (IlID,Ilce) values (31,'Samandað')
insert into Ilceler (IlID,Ilce) values (31,'Yayladaðý')

-- 32 Ýlçesi
insert into Ilceler (IlID,Ilce) values (32,'Aksu')
insert into Ilceler (IlID,Ilce) values (32,'Atabey')
insert into Ilceler (IlID,Ilce) values (32,'Eðirdir')
insert into Ilceler (IlID,Ilce) values (32,'Gelendost')
insert into Ilceler (IlID,Ilce) values (32,'Gönen')
insert into Ilceler (IlID,Ilce) values (32,'Keçiborlu')
insert into Ilceler (IlID,Ilce) values (32,'Merkez')
insert into Ilceler (IlID,Ilce) values (32,'Senirkent')
insert into Ilceler (IlID,Ilce) values (32,'Sütçüler')
insert into Ilceler (IlID,Ilce) values (32,'Þarkikaraaðaç')
insert into Ilceler (IlID,Ilce) values (32,'Uluborlu')
insert into Ilceler (IlID,Ilce) values (32,'Yalvaç')
insert into Ilceler (IlID,Ilce) values (32,'Yeniþarbademli')
--- keremozer.com
-- 33 Ýlçesi
insert into Ilceler (IlID,Ilce) values (33,'Akdeniz')
insert into Ilceler (IlID,Ilce) values (33,'Anamur')
insert into Ilceler (IlID,Ilce) values (33,'Aydýncýk')
insert into Ilceler (IlID,Ilce) values (33,'Bozyazý')
insert into Ilceler (IlID,Ilce) values (33,'Çamlýyayla')
insert into Ilceler (IlID,Ilce) values (33,'Erdemli')
insert into Ilceler (IlID,Ilce) values (33,'Gülnar')
insert into Ilceler (IlID,Ilce) values (33,'Mezitli')
insert into Ilceler (IlID,Ilce) values (33,'Mut')
insert into Ilceler (IlID,Ilce) values (33,'Silifke')
insert into Ilceler (IlID,Ilce) values (33,'Tarsus')
insert into Ilceler (IlID,Ilce) values (33,'Tarsus')
insert into Ilceler (IlID,Ilce) values (33,'Yeniþehir')

-- 34 Ýlçesi
insert into Ilceler (IlID,Ilce) values (34,'Adalar')
insert into Ilceler (IlID,Ilce) values (34,'Arnavutköy')
insert into Ilceler (IlID,Ilce) values (34,'Ataþehir')
insert into Ilceler (IlID,Ilce) values (34,'Avcýlar')
insert into Ilceler (IlID,Ilce) values (34,'Baðcýlar')
insert into Ilceler (IlID,Ilce) values (34,'Bahçelievler')
insert into Ilceler (IlID,Ilce) values (34,'Bakýrköy')
insert into Ilceler (IlID,Ilce) values (34,'Baþakþehir')
insert into Ilceler (IlID,Ilce) values (34,'Bayrampaþa')
insert into Ilceler (IlID,Ilce) values (34,'Beþiktaþ')
insert into Ilceler (IlID,Ilce) values (34,'Beykoz')
insert into Ilceler (IlID,Ilce) values (34,'Beylikdüzü')
insert into Ilceler (IlID,Ilce) values (34,'Beyoðlu')
insert into Ilceler (IlID,Ilce) values (34,'Büyükçekmece')
insert into Ilceler (IlID,Ilce) values (34,'Çatalca')
insert into Ilceler (IlID,Ilce) values (34,'Çekmeköy')
insert into Ilceler (IlID,Ilce) values (34,'Esenler')
insert into Ilceler (IlID,Ilce) values (34,'Esenyurt')
insert into Ilceler (IlID,Ilce) values (34,'Eyüp')
insert into Ilceler (IlID,Ilce) values (34,'Fatih')
insert into Ilceler (IlID,Ilce) values (34,'Gaziosmanpaþa')
insert into Ilceler (IlID,Ilce) values (34,'Güngören')
insert into Ilceler (IlID,Ilce) values (34,'Kadýköy')
insert into Ilceler (IlID,Ilce) values (34,'Kaðýthane')
insert into Ilceler (IlID,Ilce) values (34,'Kartal')
insert into Ilceler (IlID,Ilce) values (34,'Küçükçekmece')
insert into Ilceler (IlID,Ilce) values (34,'Maltepe')
insert into Ilceler (IlID,Ilce) values (34,'Pendik')
insert into Ilceler (IlID,Ilce) values (34,'Sancaktepe')
insert into Ilceler (IlID,Ilce) values (34,'Sarýyer')
insert into Ilceler (IlID,Ilce) values (34,'Silivri')
insert into Ilceler (IlID,Ilce) values (34,'Sultanbeyli')
insert into Ilceler (IlID,Ilce) values (34,'Sultangazi')
insert into Ilceler (IlID,Ilce) values (34,'Þile')
insert into Ilceler (IlID,Ilce) values (34,'Þiþli')
insert into Ilceler (IlID,Ilce) values (34,'Tuzla')
insert into Ilceler (IlID,Ilce) values (34,'Ümraniye')
insert into Ilceler (IlID,Ilce) values (34,'Üsküdar')
insert into Ilceler (IlID,Ilce) values (34,'Zeytinburnu')

-- 35 Ýlçesi
insert into Ilceler (IlID,Ilce) values (35,'Aliaða')
insert into Ilceler (IlID,Ilce) values (35,'Balçova')
insert into Ilceler (IlID,Ilce) values (35,'Bayýndýr')
insert into Ilceler (IlID,Ilce) values (35,'Bayraklý')
insert into Ilceler (IlID,Ilce) values (35,'Bergama')
insert into Ilceler (IlID,Ilce) values (35,'Beydað')
insert into Ilceler (IlID,Ilce) values (35,'Bornova')
insert into Ilceler (IlID,Ilce) values (35,'Buca')
insert into Ilceler (IlID,Ilce) values (35,'Çeþme')
insert into Ilceler (IlID,Ilce) values (35,'Çiðli')
insert into Ilceler (IlID,Ilce) values (35,'Dikili')
insert into Ilceler (IlID,Ilce) values (35,'Foça')
insert into Ilceler (IlID,Ilce) values (35,'Gaziemir')
insert into Ilceler (IlID,Ilce) values (35,'Güzelbahçe')
insert into Ilceler (IlID,Ilce) values (35,'Karabaðlar')
insert into Ilceler (IlID,Ilce) values (35,'Karaburun')
insert into Ilceler (IlID,Ilce) values (35,'Karþýyaka')
insert into Ilceler (IlID,Ilce) values (35,'Kemalpaþa')
insert into Ilceler (IlID,Ilce) values (35,'Kýnýk')
insert into Ilceler (IlID,Ilce) values (35,'Kiraz')
insert into Ilceler (IlID,Ilce) values (35,'Konak')
insert into Ilceler (IlID,Ilce) values (35,'Menderes')
insert into Ilceler (IlID,Ilce) values (35,'Menemen')
insert into Ilceler (IlID,Ilce) values (35,'Narlýdere')
insert into Ilceler (IlID,Ilce) values (35,'Ödemiþ')
insert into Ilceler (IlID,Ilce) values (35,'Seferihisar')
insert into Ilceler (IlID,Ilce) values (35,'Selçuk')
insert into Ilceler (IlID,Ilce) values (35,'Tire')
insert into Ilceler (IlID,Ilce) values (35,'Torbalý')
insert into Ilceler (IlID,Ilce) values (35,'Urla')

-- 36 Ýlçesi
insert into Ilceler (IlID,Ilce) values (36,'Akyaka')
insert into Ilceler (IlID,Ilce) values (36,'Arpaçay')
insert into Ilceler (IlID,Ilce) values (36,'Digor')
insert into Ilceler (IlID,Ilce) values (36,'Kaðýzman')
insert into Ilceler (IlID,Ilce) values (36,'Merkez')
insert into Ilceler (IlID,Ilce) values (36,'Sarýkamýþ')
insert into Ilceler (IlID,Ilce) values (36,'Selim')
insert into Ilceler (IlID,Ilce) values (36,'Susuz')

-- 37 Ýlçesi
insert into Ilceler (IlID,Ilce) values (37,'Abana')
insert into Ilceler (IlID,Ilce) values (37,'Aðlý')
insert into Ilceler (IlID,Ilce) values (37,'Araç')
insert into Ilceler (IlID,Ilce) values (37,'Azdavay')
insert into Ilceler (IlID,Ilce) values (37,'Bozkurt')
insert into Ilceler (IlID,Ilce) values (37,'Cide')
insert into Ilceler (IlID,Ilce) values (37,'Çatalzeytin')
insert into Ilceler (IlID,Ilce) values (37,'Daday')
insert into Ilceler (IlID,Ilce) values (37,'Devrekani')
insert into Ilceler (IlID,Ilce) values (37,'Doðanyurt')
insert into Ilceler (IlID,Ilce) values (37,'Hanönü')
insert into Ilceler (IlID,Ilce) values (37,'Ýhsangazi')
insert into Ilceler (IlID,Ilce) values (37,'Ýnebolu')
insert into Ilceler (IlID,Ilce) values (37,'Küre')
insert into Ilceler (IlID,Ilce) values (37,'Merkez')
insert into Ilceler (IlID,Ilce) values (37,'Pýnarbaþý')
insert into Ilceler (IlID,Ilce) values (37,'Seydiler')
insert into Ilceler (IlID,Ilce) values (37,'Þenpazar')
insert into Ilceler (IlID,Ilce) values (37,'Taþköprü')
insert into Ilceler (IlID,Ilce) values (37,'Tosya')

-- 38 Ýlçesi
insert into Ilceler (IlID,Ilce) values (38,'Akkýþla')
insert into Ilceler (IlID,Ilce) values (38,'Bünyan')
insert into Ilceler (IlID,Ilce) values (38,'Develi')
insert into Ilceler (IlID,Ilce) values (38,'Felahiye')
insert into Ilceler (IlID,Ilce) values (38,'Hacýlar')
insert into Ilceler (IlID,Ilce) values (38,'Ýncesu')
insert into Ilceler (IlID,Ilce) values (38,'Kocasinan')
insert into Ilceler (IlID,Ilce) values (38,'Melikgazi')
insert into Ilceler (IlID,Ilce) values (38,'Özvatan')
insert into Ilceler (IlID,Ilce) values (38,'Pýnarbaþý')
insert into Ilceler (IlID,Ilce) values (38,'Sarýoðlan')
insert into Ilceler (IlID,Ilce) values (38,'Sarýz')
insert into Ilceler (IlID,Ilce) values (38,'Talas')
insert into Ilceler (IlID,Ilce) values (38,'Tomarza')
insert into Ilceler (IlID,Ilce) values (38,'Yahyalý')
insert into Ilceler (IlID,Ilce) values (38,'Yeþilhisar')

-- 39 Ýlçesi
insert into Ilceler (IlID,Ilce) values (39,'Babaeski')
insert into Ilceler (IlID,Ilce) values (39,'Demirköy')
insert into Ilceler (IlID,Ilce) values (39,'Kofçaz')
insert into Ilceler (IlID,Ilce) values (39,'Lüleburgaz')
insert into Ilceler (IlID,Ilce) values (39,'Merkez')
insert into Ilceler (IlID,Ilce) values (39,'Pehlivanköy')
insert into Ilceler (IlID,Ilce) values (39,'Pýnarhisar')
insert into Ilceler (IlID,Ilce) values (39,'Vize')

-- 40 Ýlçesi
insert into Ilceler (IlID,Ilce) values (40,'Akçakent')
insert into Ilceler (IlID,Ilce) values (40,'Akpýnar')
insert into Ilceler (IlID,Ilce) values (40,'Boztepe')
insert into Ilceler (IlID,Ilce) values (40,'Çiçekdaðý')
insert into Ilceler (IlID,Ilce) values (40,'Kaman')
insert into Ilceler (IlID,Ilce) values (40,'Merkez')
insert into Ilceler (IlID,Ilce) values (40,'Mucur')

-- 41 Ýlçesi
insert into Ilceler (IlID,Ilce) values (41,'Baþiskele')
insert into Ilceler (IlID,Ilce) values (41,'Çayýrova')
insert into Ilceler (IlID,Ilce) values (41,'Darýca')
insert into Ilceler (IlID,Ilce) values (41,'Derince')
insert into Ilceler (IlID,Ilce) values (41,'Dilovasý')
insert into Ilceler (IlID,Ilce) values (41,'Gebze')
insert into Ilceler (IlID,Ilce) values (41,'Gölcük')
insert into Ilceler (IlID,Ilce) values (41,'Ýzmit')
insert into Ilceler (IlID,Ilce) values (41,'Kandýra')
insert into Ilceler (IlID,Ilce) values (41,'Karamürsel')
insert into Ilceler (IlID,Ilce) values (41,'Kartepe')
insert into Ilceler (IlID,Ilce) values (41,'Körfez')

-- 42 Ýlçesi
insert into Ilceler (IlID,Ilce) values (42,'Ahýrlý')
insert into Ilceler (IlID,Ilce) values (42,'Akören')
insert into Ilceler (IlID,Ilce) values (42,'Akþehir')
insert into Ilceler (IlID,Ilce) values (42,'Altýnekin')
insert into Ilceler (IlID,Ilce) values (42,'Beyþehir')
insert into Ilceler (IlID,Ilce) values (42,'Bozkýr')
insert into Ilceler (IlID,Ilce) values (42,'Cihanbeyli')
insert into Ilceler (IlID,Ilce) values (42,'Çeltik')
insert into Ilceler (IlID,Ilce) values (42,'Çumra')
insert into Ilceler (IlID,Ilce) values (42,'Derbent')
insert into Ilceler (IlID,Ilce) values (42,'Derebucak')
insert into Ilceler (IlID,Ilce) values (42,'Doðanhisar')
insert into Ilceler (IlID,Ilce) values (42,'Emirgazi')
insert into Ilceler (IlID,Ilce) values (42,'Ereðli')
insert into Ilceler (IlID,Ilce) values (42,'Güneysýnýr')
insert into Ilceler (IlID,Ilce) values (42,'Hadim')
insert into Ilceler (IlID,Ilce) values (42,'Halkapýnar')
insert into Ilceler (IlID,Ilce) values (42,'Hüyük')
insert into Ilceler (IlID,Ilce) values (42,'Ilgýn')
insert into Ilceler (IlID,Ilce) values (42,'Kadýnhaný')
insert into Ilceler (IlID,Ilce) values (42,'Karapýnar')
insert into Ilceler (IlID,Ilce) values (42,'Karatay')
insert into Ilceler (IlID,Ilce) values (42,'Kulu')
insert into Ilceler (IlID,Ilce) values (42,'Meram')
insert into Ilceler (IlID,Ilce) values (42,'Sarayönü')
insert into Ilceler (IlID,Ilce) values (42,'Selçuklu')
insert into Ilceler (IlID,Ilce) values (42,'Seydiþehir')
insert into Ilceler (IlID,Ilce) values (42,'Taþkent')
insert into Ilceler (IlID,Ilce) values (42,'Tuzlukçu')
insert into Ilceler (IlID,Ilce) values (42,'Yalýhüyük')
insert into Ilceler (IlID,Ilce) values (42,'Yunak')

-- 43 Ýlçesi
insert into Ilceler (IlID,Ilce) values (43,'Altýntaþ')
insert into Ilceler (IlID,Ilce) values (43,'Aslanapa')
insert into Ilceler (IlID,Ilce) values (43,'Çavdarhisar')
insert into Ilceler (IlID,Ilce) values (43,'Domaniç')
insert into Ilceler (IlID,Ilce) values (43,'Dumlupýnar')
insert into Ilceler (IlID,Ilce) values (43,'Emet')
insert into Ilceler (IlID,Ilce) values (43,'Gediz')
insert into Ilceler (IlID,Ilce) values (43,'Hisarcýk')
insert into Ilceler (IlID,Ilce) values (43,'Merkez')
insert into Ilceler (IlID,Ilce) values (43,'Pazarlar')
insert into Ilceler (IlID,Ilce) values (43,'Simav')
insert into Ilceler (IlID,Ilce) values (43,'Þaphane')
insert into Ilceler (IlID,Ilce) values (43,'Tavþanlý')
--- keremozer.com
-- 44 Ýlçesi
insert into Ilceler (IlID,Ilce) values (44,'Akçadað')
insert into Ilceler (IlID,Ilce) values (44,'Arapgir')
insert into Ilceler (IlID,Ilce) values (44,'Arguvan')
insert into Ilceler (IlID,Ilce) values (44,'Battalgazi')
insert into Ilceler (IlID,Ilce) values (44,'Darende')
insert into Ilceler (IlID,Ilce) values (44,'Doðanþehir')
insert into Ilceler (IlID,Ilce) values (44,'Doðanyol')
insert into Ilceler (IlID,Ilce) values (44,'Hekimhan')
insert into Ilceler (IlID,Ilce) values (44,'Kale')
insert into Ilceler (IlID,Ilce) values (44,'Kuluncak')
insert into Ilceler (IlID,Ilce) values (44,'Pütürge')
insert into Ilceler (IlID,Ilce) values (44,'Yazýhan')
insert into Ilceler (IlID,Ilce) values (44,'Yeþilyurt')

-- 45 Ýlçesi
insert into Ilceler (IlID,Ilce) values (45,'Ahmetli')
insert into Ilceler (IlID,Ilce) values (45,'Akhisar')
insert into Ilceler (IlID,Ilce) values (45,'Alaþehir')
insert into Ilceler (IlID,Ilce) values (45,'Demirci')
insert into Ilceler (IlID,Ilce) values (45,'Gölmarmara')
insert into Ilceler (IlID,Ilce) values (45,'Gördes')
insert into Ilceler (IlID,Ilce) values (45,'Kýrkaðaç')
insert into Ilceler (IlID,Ilce) values (45,'Köprübaþý')
insert into Ilceler (IlID,Ilce) values (45,'Kula')
insert into Ilceler (IlID,Ilce) values (45,'Salihli')
insert into Ilceler (IlID,Ilce) values (45,'Sarýgöl')
insert into Ilceler (IlID,Ilce) values (45,'Saruhanlý')
insert into Ilceler (IlID,Ilce) values (45,'Selendi')
insert into Ilceler (IlID,Ilce) values (45,'Soma')
insert into Ilceler (IlID,Ilce) values (45,'Þehzadeler')
insert into Ilceler (IlID,Ilce) values (45,'Turgutlu')
insert into Ilceler (IlID,Ilce) values (45,'Yunusemre')

-- 46 Ýlçesi
insert into Ilceler (IlID,Ilce) values (46,'Afþin')
insert into Ilceler (IlID,Ilce) values (46,'Andýrýn')
insert into Ilceler (IlID,Ilce) values (46,'Çaðlayancerit')
insert into Ilceler (IlID,Ilce) values (46,'Dulkadiroðlu')
insert into Ilceler (IlID,Ilce) values (46,'Ekinözü')
insert into Ilceler (IlID,Ilce) values (46,'Elbistan')
insert into Ilceler (IlID,Ilce) values (46,'Göksun')
insert into Ilceler (IlID,Ilce) values (46,'Nurhak')
insert into Ilceler (IlID,Ilce) values (46,'Onikiþubat')
insert into Ilceler (IlID,Ilce) values (46,'Pazarcýk')
insert into Ilceler (IlID,Ilce) values (46,'Türkoðlu')
--- keremozer.com
-- 47 Ýlçesi
insert into Ilceler (IlID,Ilce) values (47,'Artuklu')
insert into Ilceler (IlID,Ilce) values (47,'Dargeçit')
insert into Ilceler (IlID,Ilce) values (47,'Derik')
insert into Ilceler (IlID,Ilce) values (47,'Kýzýltepe')
insert into Ilceler (IlID,Ilce) values (47,'Mazýdaðý')
insert into Ilceler (IlID,Ilce) values (47,'Midyat')
insert into Ilceler (IlID,Ilce) values (47,'Nusaybin')
insert into Ilceler (IlID,Ilce) values (47,'Ömerli')
insert into Ilceler (IlID,Ilce) values (47,'Savur')
insert into Ilceler (IlID,Ilce) values (47,'Yeþilli')

-- 48 Ýlçesi
insert into Ilceler (IlID,Ilce) values (48,'Bodrum')
insert into Ilceler (IlID,Ilce) values (48,'Dalaman')
insert into Ilceler (IlID,Ilce) values (48,'Datça')
insert into Ilceler (IlID,Ilce) values (48,'Fethiye')
insert into Ilceler (IlID,Ilce) values (48,'Kavaklýdere')
insert into Ilceler (IlID,Ilce) values (48,'Köyceðiz')
insert into Ilceler (IlID,Ilce) values (48,'Marmaris')
insert into Ilceler (IlID,Ilce) values (48,'Menteþe')
insert into Ilceler (IlID,Ilce) values (48,'Milas')
insert into Ilceler (IlID,Ilce) values (48,'Ortaca')
insert into Ilceler (IlID,Ilce) values (48,'Seydikemer')
insert into Ilceler (IlID,Ilce) values (48,'Ula')
insert into Ilceler (IlID,Ilce) values (48,'Yataðan')

-- 49 Ýlçesi
insert into Ilceler (IlID,Ilce) values (49,'Bulanýk')
insert into Ilceler (IlID,Ilce) values (49,'Hasköy')
insert into Ilceler (IlID,Ilce) values (49,'Korkut')
insert into Ilceler (IlID,Ilce) values (49,'Malazgirt')
insert into Ilceler (IlID,Ilce) values (49,'Merkez')
insert into Ilceler (IlID,Ilce) values (49,'Varto')

-- 50 Ýlçesi
insert into Ilceler (IlID,Ilce) values (50,'Acýgöl')
insert into Ilceler (IlID,Ilce) values (50,'Avanos')
insert into Ilceler (IlID,Ilce) values (50,'Derinkuyu')
insert into Ilceler (IlID,Ilce) values (50,'Gülþehir')
insert into Ilceler (IlID,Ilce) values (50,'Hacýbektaþ')
insert into Ilceler (IlID,Ilce) values (50,'Kozaklý')
insert into Ilceler (IlID,Ilce) values (50,'Merkez')
insert into Ilceler (IlID,Ilce) values (50,'Ürgüp')

-- 51 Ýlçesi
insert into Ilceler (IlID,Ilce) values (51,'Altunhisar')
insert into Ilceler (IlID,Ilce) values (51,'Bor')
insert into Ilceler (IlID,Ilce) values (51,'Çamardý')
insert into Ilceler (IlID,Ilce) values (51,'Çiftlik')
insert into Ilceler (IlID,Ilce) values (51,'Merkez')
insert into Ilceler (IlID,Ilce) values (51,'Ulukýþla')
--- keremozer.com
-- 52 Ýlçesi
insert into Ilceler (IlID,Ilce) values (52,'Akkuþ')
insert into Ilceler (IlID,Ilce) values (52,'Altýnordu')
insert into Ilceler (IlID,Ilce) values (52,'Aybastý')
insert into Ilceler (IlID,Ilce) values (52,'Çamaþ')
insert into Ilceler (IlID,Ilce) values (52,'Çatalpýnar')
insert into Ilceler (IlID,Ilce) values (52,'Çaybaþý')
insert into Ilceler (IlID,Ilce) values (52,'Fatsa')
insert into Ilceler (IlID,Ilce) values (52,'Gölköy')
insert into Ilceler (IlID,Ilce) values (52,'Gülyalý')
insert into Ilceler (IlID,Ilce) values (52,'Gürgentepe')
insert into Ilceler (IlID,Ilce) values (52,'Ýkizce')
insert into Ilceler (IlID,Ilce) values (52,'Kabadüz')
insert into Ilceler (IlID,Ilce) values (52,'Kabataþ')
insert into Ilceler (IlID,Ilce) values (52,'Korgan')
insert into Ilceler (IlID,Ilce) values (52,'Kumru')
insert into Ilceler (IlID,Ilce) values (52,'Mesudiye')
insert into Ilceler (IlID,Ilce) values (52,'Perþembe')
insert into Ilceler (IlID,Ilce) values (52,'Ulubey')
insert into Ilceler (IlID,Ilce) values (52,'Ünye')

-- 53 Ýlçesi
insert into Ilceler (IlID,Ilce) values (53,'Ardeþen')
insert into Ilceler (IlID,Ilce) values (53,'Çamlýhemþin')
insert into Ilceler (IlID,Ilce) values (53,'Çayeli')
insert into Ilceler (IlID,Ilce) values (53,'Derepazarý')
insert into Ilceler (IlID,Ilce) values (53,'Fýndýklý')
insert into Ilceler (IlID,Ilce) values (53,'Güneysu')
insert into Ilceler (IlID,Ilce) values (53,'Hemþin')
insert into Ilceler (IlID,Ilce) values (53,'Ýkizdere')
insert into Ilceler (IlID,Ilce) values (53,'Ýyidere')
insert into Ilceler (IlID,Ilce) values (53,'Kalkandere')
insert into Ilceler (IlID,Ilce) values (53,'Merkez')
insert into Ilceler (IlID,Ilce) values (53,'Pazar')
--- keremozer.com
-- 54 Ýlçesi
insert into Ilceler (IlID,Ilce) values (54,'Adapazarý')
insert into Ilceler (IlID,Ilce) values (54,'Akyazý')
insert into Ilceler (IlID,Ilce) values (54,'Arifiye')
insert into Ilceler (IlID,Ilce) values (54,'Erenler')
insert into Ilceler (IlID,Ilce) values (54,'Ferizli')
insert into Ilceler (IlID,Ilce) values (54,'Geyve')
insert into Ilceler (IlID,Ilce) values (54,'Hendek')
insert into Ilceler (IlID,Ilce) values (54,'Karapürçek')
insert into Ilceler (IlID,Ilce) values (54,'Karasu')
insert into Ilceler (IlID,Ilce) values (54,'Kaynarca')
insert into Ilceler (IlID,Ilce) values (54,'Kocaali')
insert into Ilceler (IlID,Ilce) values (54,'Pamukova')
insert into Ilceler (IlID,Ilce) values (54,'Sapanca')
insert into Ilceler (IlID,Ilce) values (54,'Serdivan')
insert into Ilceler (IlID,Ilce) values (54,'Söðütlü')
insert into Ilceler (IlID,Ilce) values (54,'Taraklý')

-- 55 Ýlçesi
insert into Ilceler (IlID,Ilce) values (55,'19 Mayýs')
insert into Ilceler (IlID,Ilce) values (55,'Alaçam')
insert into Ilceler (IlID,Ilce) values (55,'Asarcýk')
insert into Ilceler (IlID,Ilce) values (55,'Atakum')
insert into Ilceler (IlID,Ilce) values (55,'Ayvacýk')
insert into Ilceler (IlID,Ilce) values (55,'Bafra')
insert into Ilceler (IlID,Ilce) values (55,'Canik')
insert into Ilceler (IlID,Ilce) values (55,'Çarþamba')
insert into Ilceler (IlID,Ilce) values (55,'Havza')
insert into Ilceler (IlID,Ilce) values (55,'Ýlkadým')
insert into Ilceler (IlID,Ilce) values (55,'Kavak')
insert into Ilceler (IlID,Ilce) values (55,'Ladik')
insert into Ilceler (IlID,Ilce) values (55,'Salýpazarý')
insert into Ilceler (IlID,Ilce) values (55,'Tekkeköy')
insert into Ilceler (IlID,Ilce) values (55,'Terme')
insert into Ilceler (IlID,Ilce) values (55,'Vezirköprü')
insert into Ilceler (IlID,Ilce) values (55,'Yakakent')

-- 56 Ýlçesi
insert into Ilceler (IlID,Ilce) values (56,'Baykan')
insert into Ilceler (IlID,Ilce) values (56,'Eruh')
insert into Ilceler (IlID,Ilce) values (56,'Kurtalan')
insert into Ilceler (IlID,Ilce) values (56,'Merkez')
insert into Ilceler (IlID,Ilce) values (56,'Pervari')
insert into Ilceler (IlID,Ilce) values (56,'Þirvan')
insert into Ilceler (IlID,Ilce) values (56,'Tillo')

-- 57 Ýlçesi
insert into Ilceler (IlID,Ilce) values (57,'Ayancýk')
insert into Ilceler (IlID,Ilce) values (57,'Boyabat')
insert into Ilceler (IlID,Ilce) values (57,'Dikmen')
insert into Ilceler (IlID,Ilce) values (57,'Duraðan')
insert into Ilceler (IlID,Ilce) values (57,'Erfelek')
insert into Ilceler (IlID,Ilce) values (57,'Gerze')
insert into Ilceler (IlID,Ilce) values (57,'Merkez')
insert into Ilceler (IlID,Ilce) values (57,'Saraydüzü')
insert into Ilceler (IlID,Ilce) values (57,'Türkeli')

-- 58 Ýlçesi
insert into Ilceler (IlID,Ilce) values (58,'Akýncýlar')
insert into Ilceler (IlID,Ilce) values (58,'Altýnyayla')
insert into Ilceler (IlID,Ilce) values (58,'Divriði')
insert into Ilceler (IlID,Ilce) values (58,'Doðanþar')
insert into Ilceler (IlID,Ilce) values (58,'Gemerek')
insert into Ilceler (IlID,Ilce) values (58,'Gölova')
insert into Ilceler (IlID,Ilce) values (58,'Gürün')
insert into Ilceler (IlID,Ilce) values (58,'Hafik')
insert into Ilceler (IlID,Ilce) values (58,'Ýmranlý')
insert into Ilceler (IlID,Ilce) values (58,'Kangal')
insert into Ilceler (IlID,Ilce) values (58,'Koyulhisar')
insert into Ilceler (IlID,Ilce) values (58,'Merkez')
insert into Ilceler (IlID,Ilce) values (58,'Suþehri')
insert into Ilceler (IlID,Ilce) values (58,'Þarkýþla')
insert into Ilceler (IlID,Ilce) values (58,'Ulaþ')
insert into Ilceler (IlID,Ilce) values (58,'Yýldýzeli')
insert into Ilceler (IlID,Ilce) values (58,'Zara')

-- 59 Ýlçesi
insert into Ilceler (IlID,Ilce) values (59,'Çerkezköy')
insert into Ilceler (IlID,Ilce) values (59,'Çorlu')
insert into Ilceler (IlID,Ilce) values (59,'Ergene')
insert into Ilceler (IlID,Ilce) values (59,'Hayrabolu')
insert into Ilceler (IlID,Ilce) values (59,'Malkara')
insert into Ilceler (IlID,Ilce) values (59,'Marmaraereðlisi')
insert into Ilceler (IlID,Ilce) values (59,'Muratlý')
insert into Ilceler (IlID,Ilce) values (59,'Saray')
insert into Ilceler (IlID,Ilce) values (59,'Süleymanpaþa')
insert into Ilceler (IlID,Ilce) values (59,'Þarköy')
--- keremozer.com
-- 60 Ýlçesi
insert into Ilceler (IlID,Ilce) values (60,'Almus')
insert into Ilceler (IlID,Ilce) values (60,'Artova')
insert into Ilceler (IlID,Ilce) values (60,'Baþçiftlik')
insert into Ilceler (IlID,Ilce) values (60,'Erbaa')
insert into Ilceler (IlID,Ilce) values (60,'Merkez')
insert into Ilceler (IlID,Ilce) values (60,'Niksar')
insert into Ilceler (IlID,Ilce) values (60,'Pazar')
insert into Ilceler (IlID,Ilce) values (60,'Reþadiye')
insert into Ilceler (IlID,Ilce) values (60,'Sulusaray')
insert into Ilceler (IlID,Ilce) values (60,'Turhal')
insert into Ilceler (IlID,Ilce) values (60,'Yeþilyurt')
insert into Ilceler (IlID,Ilce) values (60,'Zile')

-- 61 Ýlçesi
insert into Ilceler (IlID,Ilce) values (61,'Akçaabat')
insert into Ilceler (IlID,Ilce) values (61,'Araklý')
insert into Ilceler (IlID,Ilce) values (61,'Arsin')
insert into Ilceler (IlID,Ilce) values (61,'Beþikdüzü')
insert into Ilceler (IlID,Ilce) values (61,'Çarþýbaþý')
insert into Ilceler (IlID,Ilce) values (61,'Çaykara')
insert into Ilceler (IlID,Ilce) values (61,'Dernekpazarý')
insert into Ilceler (IlID,Ilce) values (61,'Düzköy')
insert into Ilceler (IlID,Ilce) values (61,'Hayrat')
insert into Ilceler (IlID,Ilce) values (61,'Köprübaþý')
insert into Ilceler (IlID,Ilce) values (61,'Maçka')
insert into Ilceler (IlID,Ilce) values (61,'Of')
insert into Ilceler (IlID,Ilce) values (61,'Ortahisar')
insert into Ilceler (IlID,Ilce) values (61,'Sürmene')
insert into Ilceler (IlID,Ilce) values (61,'Þalpazarý')
insert into Ilceler (IlID,Ilce) values (61,'Tonya')
insert into Ilceler (IlID,Ilce) values (61,'Vakfýkebir')
insert into Ilceler (IlID,Ilce) values (61,'Yomra')

-- 62 Ýlçesi
insert into Ilceler (IlID,Ilce) values (62,'Çemiþgezek')
insert into Ilceler (IlID,Ilce) values (62,'Hozat')
insert into Ilceler (IlID,Ilce) values (62,'Mazgirt')
insert into Ilceler (IlID,Ilce) values (62,'Merkez')
insert into Ilceler (IlID,Ilce) values (62,'Nazýmiye')
insert into Ilceler (IlID,Ilce) values (62,'Ovacýk')
insert into Ilceler (IlID,Ilce) values (62,'Pertek')
insert into Ilceler (IlID,Ilce) values (62,'Pülümür')

-- 63 Ýlçesi
insert into Ilceler (IlID,Ilce) values (63,'Akçakale')
insert into Ilceler (IlID,Ilce) values (63,'Birecik')
insert into Ilceler (IlID,Ilce) values (63,'Bozova')
insert into Ilceler (IlID,Ilce) values (63,'Ceylanpýnar')
insert into Ilceler (IlID,Ilce) values (63,'Eyyübiye')
insert into Ilceler (IlID,Ilce) values (63,'Halfeti')
insert into Ilceler (IlID,Ilce) values (63,'Haliliye')
insert into Ilceler (IlID,Ilce) values (63,'Harran')
insert into Ilceler (IlID,Ilce) values (63,'Hilvan')
insert into Ilceler (IlID,Ilce) values (63,'Karaköprü')
insert into Ilceler (IlID,Ilce) values (63,'Siverek')
insert into Ilceler (IlID,Ilce) values (63,'Suruç')
insert into Ilceler (IlID,Ilce) values (63,'Viranþehir')
--- keremozer.com
-- 64 Ýlçesi
insert into Ilceler (IlID,Ilce) values (64,'Banaz')
insert into Ilceler (IlID,Ilce) values (64,'Eþme')
insert into Ilceler (IlID,Ilce) values (64,'Karahallý')
insert into Ilceler (IlID,Ilce) values (64,'Merkez')
insert into Ilceler (IlID,Ilce) values (64,'Sivaslý')
insert into Ilceler (IlID,Ilce) values (64,'Ulubey')

-- 65 Ýlçesi
insert into Ilceler (IlID,Ilce) values (65,'Bahçesaray')
insert into Ilceler (IlID,Ilce) values (65,'Baþkale')
insert into Ilceler (IlID,Ilce) values (65,'Çaldýran')
insert into Ilceler (IlID,Ilce) values (65,'Çatak')
insert into Ilceler (IlID,Ilce) values (65,'Edremit')
insert into Ilceler (IlID,Ilce) values (65,'Erciþ')
insert into Ilceler (IlID,Ilce) values (65,'Gevaþ')
insert into Ilceler (IlID,Ilce) values (65,'Gürpýnar')
insert into Ilceler (IlID,Ilce) values (65,'Ýpekyolu')
insert into Ilceler (IlID,Ilce) values (65,'Muradiye')
insert into Ilceler (IlID,Ilce) values (65,'Özalp')
insert into Ilceler (IlID,Ilce) values (65,'Saray')
insert into Ilceler (IlID,Ilce) values (65,'Tuþba')

-- 66 Ýlçesi
insert into Ilceler (IlID,Ilce) values (66,'Akdaðmadeni')
insert into Ilceler (IlID,Ilce) values (66,'Aydýncýk')
insert into Ilceler (IlID,Ilce) values (66,'Boðazlýyan')
insert into Ilceler (IlID,Ilce) values (66,'Çandýr')
insert into Ilceler (IlID,Ilce) values (66,'Çayýralan')
insert into Ilceler (IlID,Ilce) values (66,'Çekerek')
insert into Ilceler (IlID,Ilce) values (66,'Kadýþehri')
insert into Ilceler (IlID,Ilce) values (66,'Merkez')
insert into Ilceler (IlID,Ilce) values (66,'Saraykent')
insert into Ilceler (IlID,Ilce) values (66,'Sarýkaya')
insert into Ilceler (IlID,Ilce) values (66,'Sorgun')
insert into Ilceler (IlID,Ilce) values (66,'Þefaatli')
insert into Ilceler (IlID,Ilce) values (66,'Yenifakýlý')
insert into Ilceler (IlID,Ilce) values (66,'Yerköy')

-- 67 Ýlçesi
insert into Ilceler (IlID,Ilce) values (67,'Alaplý')
insert into Ilceler (IlID,Ilce) values (67,'Çaycuma')
insert into Ilceler (IlID,Ilce) values (67,'Devrek')
insert into Ilceler (IlID,Ilce) values (67,'Ereðli')
insert into Ilceler (IlID,Ilce) values (67,'Gökçebey')
insert into Ilceler (IlID,Ilce) values (67,'Merkez')

-- 68 Ýlçesi
insert into Ilceler (IlID,Ilce) values (68,'Aðaçören')
insert into Ilceler (IlID,Ilce) values (68,'Eskil')
insert into Ilceler (IlID,Ilce) values (68,'Gülaðaç')
insert into Ilceler (IlID,Ilce) values (68,'Güzelyurt')
insert into Ilceler (IlID,Ilce) values (68,'Merkez')
insert into Ilceler (IlID,Ilce) values (68,'Ortaköy')
insert into Ilceler (IlID,Ilce) values (68,'Sarýyahþi')

-- 69 Ýlçesi
insert into Ilceler (IlID,Ilce) values (69,'Aydýntepe')
insert into Ilceler (IlID,Ilce) values (69,'Demirözü')
insert into Ilceler (IlID,Ilce) values (69,'Merkez')

-- 70 Ýlçesi
insert into Ilceler (IlID,Ilce) values (70,'Ayrancý')
insert into Ilceler (IlID,Ilce) values (70,'Baþyayla')
insert into Ilceler (IlID,Ilce) values (70,'Ermenek')
insert into Ilceler (IlID,Ilce) values (70,'Kazýmkarabekir')
insert into Ilceler (IlID,Ilce) values (70,'Merkez')
insert into Ilceler (IlID,Ilce) values (70,'Sarýveliler')
--- keremozer.com
-- 71 Ýlçesi
insert into Ilceler (IlID,Ilce) values (71,'Bahþili')
insert into Ilceler (IlID,Ilce) values (71,'Balýþeyh')
insert into Ilceler (IlID,Ilce) values (71,'Çelebi')
insert into Ilceler (IlID,Ilce) values (71,'Delice')
insert into Ilceler (IlID,Ilce) values (71,'Karakeçili')
insert into Ilceler (IlID,Ilce) values (71,'Keskin')
insert into Ilceler (IlID,Ilce) values (71,'Merkez')
insert into Ilceler (IlID,Ilce) values (71,'Sulakyurt')
insert into Ilceler (IlID,Ilce) values (71,'Yahþihan')

-- 72 Ýlçesi
insert into Ilceler (IlID,Ilce) values (72,'Beþiri')
insert into Ilceler (IlID,Ilce) values (72,'Gercüþ')
insert into Ilceler (IlID,Ilce) values (72,'Hasankeyf')
insert into Ilceler (IlID,Ilce) values (72,'Kozluk')
insert into Ilceler (IlID,Ilce) values (72,'Merkez')
insert into Ilceler (IlID,Ilce) values (72,'Sason')

-- 73 Ýlçesi
insert into Ilceler (IlID,Ilce) values (73,'Beytüþþebap')
insert into Ilceler (IlID,Ilce) values (73,'Cizre')
insert into Ilceler (IlID,Ilce) values (73,'Güçlükonak')
insert into Ilceler (IlID,Ilce) values (73,'Ýdil')
insert into Ilceler (IlID,Ilce) values (73,'Merkez')
insert into Ilceler (IlID,Ilce) values (73,'Silopi')
insert into Ilceler (IlID,Ilce) values (73,'Uludere')

-- 74 Ýlçesi
insert into Ilceler (IlID,Ilce) values (74,'Amasra')
insert into Ilceler (IlID,Ilce) values (74,'Kurucaþile')
insert into Ilceler (IlID,Ilce) values (74,'Merkez')
insert into Ilceler (IlID,Ilce) values (74,'Ulus')

-- 75 Ýlçesi
insert into Ilceler (IlID,Ilce) values (75,'Çýldýr')
insert into Ilceler (IlID,Ilce) values (75,'Damal')
insert into Ilceler (IlID,Ilce) values (75,'Göle')
insert into Ilceler (IlID,Ilce) values (75,'Hanak')
insert into Ilceler (IlID,Ilce) values (75,'Merkez')
insert into Ilceler (IlID,Ilce) values (75,'Posof')
--- keremozer.com
-- 76 Ýlçesi
insert into Ilceler (IlID,Ilce) values (76,'Aralýk')
insert into Ilceler (IlID,Ilce) values (76,'Karakoyunlu')
insert into Ilceler (IlID,Ilce) values (76,'Merkez')
insert into Ilceler (IlID,Ilce) values (76,'Tuzluca')

-- 77 Ýlçesi
insert into Ilceler (IlID,Ilce) values (77,'Altýnova')
insert into Ilceler (IlID,Ilce) values (77,'Armutlu')
insert into Ilceler (IlID,Ilce) values (77,'Çýnarcýk')
insert into Ilceler (IlID,Ilce) values (77,'Çiftlikköy')
insert into Ilceler (IlID,Ilce) values (77,'Merkez')
insert into Ilceler (IlID,Ilce) values (77,'Termal')

-- 78 Ýlçesi
insert into Ilceler (IlID,Ilce) values (78,'Eflani')
insert into Ilceler (IlID,Ilce) values (78,'Eskipazar')
insert into Ilceler (IlID,Ilce) values (78,'Merkez')
insert into Ilceler (IlID,Ilce) values (78,'Ovacýk')
insert into Ilceler (IlID,Ilce) values (78,'Safranbolu')
insert into Ilceler (IlID,Ilce) values (78,'Yenice')

-- 79 Ýlçesi
insert into Ilceler (IlID,Ilce) values (79,'Elbeyli')
insert into Ilceler (IlID,Ilce) values (79,'Merkez')
insert into Ilceler (IlID,Ilce) values (79,'Musabeyli')
insert into Ilceler (IlID,Ilce) values (79,'Polateli')

-- 80 Ýlçesi
insert into Ilceler (IlID,Ilce) values (80,'Bahçe')
insert into Ilceler (IlID,Ilce) values (80,'Düziçi')
insert into Ilceler (IlID,Ilce) values (80,'Hasanbeyli')
insert into Ilceler (IlID,Ilce) values (80,'Kadirli')
insert into Ilceler (IlID,Ilce) values (80,'Merkez')
insert into Ilceler (IlID,Ilce) values (80,'Sumbas')
insert into Ilceler (IlID,Ilce) values (80,'Toprakkale')

-- 81 Ýlçesi
insert into Ilceler (IlID,Ilce) values (81,'Akçakoca')
insert into Ilceler (IlID,Ilce) values (81,'Cumayeri')
insert into Ilceler (IlID,Ilce) values (81,'Çilimli')
insert into Ilceler (IlID,Ilce) values (81,'Gölyaka')
insert into Ilceler (IlID,Ilce) values (81,'Gümüþova')
insert into Ilceler (IlID,Ilce) values (81,'Kaynaþlý')
insert into Ilceler (IlID,Ilce) values (81,'Merkez')
insert into Ilceler (IlID,Ilce) values (81,'Yýðýlca')

--- keremozer.com